version: '3.7'

services:

  mongo:
    container_name: practice_mongo
    image: mongo
    volumes:
      - practice_mongo_data:/data/mongo
    ports:
      - "27017:27017"

    env_file:
      - .env

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    restart: always

  postgres:
    container_name: practice_postgres
    image: postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    env_file:
      - .env

    ports:
      - "127.0.0.1:5433:5432"

    volumes:
      - practice_postgres_data:/data

    restart: always

  redis:
    container_name: practice_redis

    image: redis:7.2-alpine
    volumes:
      - practice_redis_data:/data

    restart: always

  api_gateway:
    container_name: api_gateway_container
    build: api_gateway

    env_file:
      - .env

    command: bash -c "uvicorn app:app --reload --host 0.0.0.0 --port 8000"

    ports:
      - 8000:8000


    restart: always

  user_service:
    container_name: user_service_container
    build: user_service

    env_file:
      - .env

    command: bash -c "alembic upgrade head && uvicorn app:app --reload --host 0.0.0.0 --port 8080"

    depends_on:
      - postgres
      - redis
      - api_gateway

    ports:
      - 8080:8080

  group_chat_service:
    container_name: group_chat_service_container
    build: group_chat_service

    env_file:
      - .env

    command: bash -c "uvicorn app:app --reload --host 0.0.0.0 --port 8070"

    depends_on:
      - api_gateway

    ports:
      - 8070:8070

  ptp_chat_service:
    container_name: ptp_chat_service_container
    build: ptp_chat_service

    env_file:
      - .env

    command: bash -c "uvicorn app:app --reload --host 0.0.0.0 --port 8090"

    depends_on:
      - api_gateway

    ports:
      - 8090:8090


volumes:
  practice_mongo_data:
  practice_postgres_data:
  practice_redis_data: